# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from pydantic import BaseModel, ConfigDict

import baml_py

from . import types

StreamStateValueT = typing.TypeVar('StreamStateValueT')
class StreamState(BaseModel, typing.Generic[StreamStateValueT]):
    value: StreamStateValueT
    state: typing_extensions.Literal["Pending", "Incomplete", "Complete"]
# #########################################################################
# Generated classes (4)
# #########################################################################

class AnswerEvidenceQuote(BaseModel):
    paper_id: typing.Optional[int] = None
    paper_title: typing.Optional[str] = None
    quote: typing.Optional[str] = None
    page: typing.Optional[int] = None
    chunk_id: typing.Optional[str] = None

class CellExtraction(BaseModel):
    status: typing.Optional[types.CellStatus] = None
    answer: typing.Optional[str] = None
    value: typing.Optional[str] = None
    evidence: typing.List["EvidenceQuote"]
    confidence: typing.Optional[types.Confidence] = None
    rationale: typing.Optional[str] = None

class EvidenceQuote(BaseModel):
    quote: typing.Optional[str] = None
    page: typing.Optional[int] = None
    chunk_id: typing.Optional[str] = None

class PaperQuestionAnswer(BaseModel):
    answer: typing.Optional[str] = None
    evidence: typing.List["AnswerEvidenceQuote"]
    confidence: typing.Optional[types.Confidence] = None
    rationale: typing.Optional[str] = None

# #########################################################################
# Generated type aliases (0)
# #########################################################################
