# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
import baml_py

from . import stream_types, types, type_builder
from .parser import LlmResponseParser, LlmStreamParser
from .runtime import DoNotUseDirectlyCallManager, BamlCallOptions
from .globals import DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_RUNTIME as __runtime__

class BamlSyncClient:
    __options: DoNotUseDirectlyCallManager
    __stream_client: "BamlStreamClient"
    __http_request: "BamlHttpRequestClient"
    __http_stream_request: "BamlHttpStreamRequestClient"
    __llm_response_parser: LlmResponseParser
    __llm_stream_parser: LlmStreamParser

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options
        self.__stream_client = BamlStreamClient(options)
        self.__http_request = BamlHttpRequestClient(options)
        self.__http_stream_request = BamlHttpStreamRequestClient(options)
        self.__llm_response_parser = LlmResponseParser(options)
        self.__llm_stream_parser = LlmStreamParser(options)

    def __getstate__(self):
        # Return state needed for pickling
        return {"options": self.__options}

    def __setstate__(self, state):
        # Restore state from pickling
        self.__options = state["options"]
        self.__stream_client = BamlStreamClient(self.__options)
        self.__http_request = BamlHttpRequestClient(self.__options)
        self.__http_stream_request = BamlHttpStreamRequestClient(self.__options)
        self.__llm_response_parser = LlmResponseParser(self.__options)
        self.__llm_stream_parser = LlmStreamParser(self.__options)

    def with_options(self,
        tb: typing.Optional[type_builder.TypeBuilder] = None,
        client_registry: typing.Optional[baml_py.baml_py.ClientRegistry] = None,
        collector: typing.Optional[typing.Union[baml_py.baml_py.Collector, typing.List[baml_py.baml_py.Collector]]] = None,
        env: typing.Optional[typing.Dict[str, typing.Optional[str]]] = None,
    ) -> "BamlSyncClient":
        options: BamlCallOptions = {}
        if tb is not None:
            options["tb"] = tb
        if client_registry is not None:
            options["client_registry"] = client_registry
        if collector is not None:
            options["collector"] = collector
        if env is not None:
            options["env"] = env
        return BamlSyncClient(self.__options.merge_options(options))

    @property
    def stream(self):
      return self.__stream_client

    @property
    def request(self):
      return self.__http_request

    @property
    def stream_request(self):
      return self.__http_stream_request

    @property
    def parse(self):
      return self.__llm_response_parser

    @property
    def parse_stream(self):
      return self.__llm_stream_parser
    
    def AnswerQuestion(self, question: str,evidence_context: str,
        baml_options: BamlCallOptions = {},
    ) -> types.PaperQuestionAnswer:
        result = self.__options.merge_options(baml_options).call_function_sync(function_name="AnswerQuestion", args={
            "question": question,"evidence_context": evidence_context,
        })
        return typing.cast(types.PaperQuestionAnswer, result.cast_to(types, types, stream_types, False, __runtime__))
    def AnswerQuestionFromContext(self, question: str,context_label: str,evidence_context: str,
        baml_options: BamlCallOptions = {},
    ) -> types.PaperQuestionAnswer:
        result = self.__options.merge_options(baml_options).call_function_sync(function_name="AnswerQuestionFromContext", args={
            "question": question,"context_label": context_label,"evidence_context": evidence_context,
        })
        return typing.cast(types.PaperQuestionAnswer, result.cast_to(types, types, stream_types, False, __runtime__))
    def ExtractCell(self, paper_title: str,column_name: str,column_prompt: str,evidence_context: str,
        baml_options: BamlCallOptions = {},
    ) -> types.CellExtraction:
        result = self.__options.merge_options(baml_options).call_function_sync(function_name="ExtractCell", args={
            "paper_title": paper_title,"column_name": column_name,"column_prompt": column_prompt,"evidence_context": evidence_context,
        })
        return typing.cast(types.CellExtraction, result.cast_to(types, types, stream_types, False, __runtime__))
    def SynthesizeQuestionAnswers(self, question: str,intermediate_answers: str,
        baml_options: BamlCallOptions = {},
    ) -> types.PaperQuestionAnswer:
        result = self.__options.merge_options(baml_options).call_function_sync(function_name="SynthesizeQuestionAnswers", args={
            "question": question,"intermediate_answers": intermediate_answers,
        })
        return typing.cast(types.PaperQuestionAnswer, result.cast_to(types, types, stream_types, False, __runtime__))
    


class BamlStreamClient:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def AnswerQuestion(self, question: str,evidence_context: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[stream_types.PaperQuestionAnswer, types.PaperQuestionAnswer]:
        ctx, result = self.__options.merge_options(baml_options).create_sync_stream(function_name="AnswerQuestion", args={
            "question": question,"evidence_context": evidence_context,
        })
        return baml_py.BamlSyncStream[stream_types.PaperQuestionAnswer, types.PaperQuestionAnswer](
          result,
          lambda x: typing.cast(stream_types.PaperQuestionAnswer, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.PaperQuestionAnswer, x.cast_to(types, types, stream_types, False, __runtime__)),
          ctx,
        )
    def AnswerQuestionFromContext(self, question: str,context_label: str,evidence_context: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[stream_types.PaperQuestionAnswer, types.PaperQuestionAnswer]:
        ctx, result = self.__options.merge_options(baml_options).create_sync_stream(function_name="AnswerQuestionFromContext", args={
            "question": question,"context_label": context_label,"evidence_context": evidence_context,
        })
        return baml_py.BamlSyncStream[stream_types.PaperQuestionAnswer, types.PaperQuestionAnswer](
          result,
          lambda x: typing.cast(stream_types.PaperQuestionAnswer, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.PaperQuestionAnswer, x.cast_to(types, types, stream_types, False, __runtime__)),
          ctx,
        )
    def ExtractCell(self, paper_title: str,column_name: str,column_prompt: str,evidence_context: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[stream_types.CellExtraction, types.CellExtraction]:
        ctx, result = self.__options.merge_options(baml_options).create_sync_stream(function_name="ExtractCell", args={
            "paper_title": paper_title,"column_name": column_name,"column_prompt": column_prompt,"evidence_context": evidence_context,
        })
        return baml_py.BamlSyncStream[stream_types.CellExtraction, types.CellExtraction](
          result,
          lambda x: typing.cast(stream_types.CellExtraction, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.CellExtraction, x.cast_to(types, types, stream_types, False, __runtime__)),
          ctx,
        )
    def SynthesizeQuestionAnswers(self, question: str,intermediate_answers: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[stream_types.PaperQuestionAnswer, types.PaperQuestionAnswer]:
        ctx, result = self.__options.merge_options(baml_options).create_sync_stream(function_name="SynthesizeQuestionAnswers", args={
            "question": question,"intermediate_answers": intermediate_answers,
        })
        return baml_py.BamlSyncStream[stream_types.PaperQuestionAnswer, types.PaperQuestionAnswer](
          result,
          lambda x: typing.cast(stream_types.PaperQuestionAnswer, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.PaperQuestionAnswer, x.cast_to(types, types, stream_types, False, __runtime__)),
          ctx,
        )
    

class BamlHttpRequestClient:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def AnswerQuestion(self, question: str,evidence_context: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="AnswerQuestion", args={
            "question": question,"evidence_context": evidence_context,
        }, mode="request")
        return result
    def AnswerQuestionFromContext(self, question: str,context_label: str,evidence_context: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="AnswerQuestionFromContext", args={
            "question": question,"context_label": context_label,"evidence_context": evidence_context,
        }, mode="request")
        return result
    def ExtractCell(self, paper_title: str,column_name: str,column_prompt: str,evidence_context: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="ExtractCell", args={
            "paper_title": paper_title,"column_name": column_name,"column_prompt": column_prompt,"evidence_context": evidence_context,
        }, mode="request")
        return result
    def SynthesizeQuestionAnswers(self, question: str,intermediate_answers: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="SynthesizeQuestionAnswers", args={
            "question": question,"intermediate_answers": intermediate_answers,
        }, mode="request")
        return result
    

class BamlHttpStreamRequestClient:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def AnswerQuestion(self, question: str,evidence_context: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="AnswerQuestion", args={
            "question": question,"evidence_context": evidence_context,
        }, mode="stream")
        return result
    def AnswerQuestionFromContext(self, question: str,context_label: str,evidence_context: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="AnswerQuestionFromContext", args={
            "question": question,"context_label": context_label,"evidence_context": evidence_context,
        }, mode="stream")
        return result
    def ExtractCell(self, paper_title: str,column_name: str,column_prompt: str,evidence_context: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="ExtractCell", args={
            "paper_title": paper_title,"column_name": column_name,"column_prompt": column_prompt,"evidence_context": evidence_context,
        }, mode="stream")
        return result
    def SynthesizeQuestionAnswers(self, question: str,intermediate_answers: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="SynthesizeQuestionAnswers", args={
            "question": question,"intermediate_answers": intermediate_answers,
        }, mode="stream")
        return result
    

b = BamlSyncClient(DoNotUseDirectlyCallManager({}))