# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from enum import Enum


from pydantic import BaseModel, ConfigDict


import baml_py

CheckT = typing_extensions.TypeVar('CheckT')
CheckName = typing_extensions.TypeVar('CheckName', bound=str)

class Check(BaseModel):
    name: str
    expression: str
    status: str
class Checked(BaseModel, typing.Generic[CheckT, CheckName]):
    value: CheckT
    checks: typing.Dict[CheckName, Check]

def get_checks(checks: typing.Dict[CheckName, Check]) -> typing.List[Check]:
    return list(checks.values())

def all_succeeded(checks: typing.Dict[CheckName, Check]) -> bool:
    return all(check.status == "succeeded" for check in get_checks(checks))
# #########################################################################
# Generated enums (2)
# #########################################################################

class CellStatus(str, Enum):
    ANSWERED = "ANSWERED"
    NOT_REPORTED = "NOT_REPORTED"
    UNCERTAIN = "UNCERTAIN"

class Confidence(str, Enum):
    HIGH = "HIGH"
    MEDIUM = "MEDIUM"
    LOW = "LOW"

# #########################################################################
# Generated classes (4)
# #########################################################################

class AnswerEvidenceQuote(BaseModel):
    paper_id: int
    paper_title: typing.Optional[str] = None
    quote: str
    page: typing.Optional[int] = None
    chunk_id: typing.Optional[str] = None

class CellExtraction(BaseModel):
    status: CellStatus
    answer: str
    value: typing.Optional[str] = None
    evidence: typing.List["EvidenceQuote"]
    confidence: Confidence
    rationale: typing.Optional[str] = None

class EvidenceQuote(BaseModel):
    quote: str
    page: typing.Optional[int] = None
    chunk_id: typing.Optional[str] = None

class PaperQuestionAnswer(BaseModel):
    answer: str
    evidence: typing.List["AnswerEvidenceQuote"]
    confidence: Confidence
    rationale: typing.Optional[str] = None

# #########################################################################
# Generated type aliases (0)
# #########################################################################
