# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

from . import types
from . import stream_types


type_map = {

    "types.AnswerEvidenceQuote": types.AnswerEvidenceQuote,
    "stream_types.AnswerEvidenceQuote": stream_types.AnswerEvidenceQuote,

    "types.CellExtraction": types.CellExtraction,
    "stream_types.CellExtraction": stream_types.CellExtraction,

    "types.EvidenceQuote": types.EvidenceQuote,
    "stream_types.EvidenceQuote": stream_types.EvidenceQuote,

    "types.PaperQuestionAnswer": types.PaperQuestionAnswer,
    "stream_types.PaperQuestionAnswer": stream_types.PaperQuestionAnswer,


    "types.CellStatus": types.CellStatus,

    "types.Confidence": types.Confidence,

}